spring.application.name=pocatcher-api

app.cors.allowed-origins=http://localhost:5173,http://localhost:4173

pokeapi.baseurl=https://pokeapi.co/api/v2
pokeapi.httpclient-connect-timeout=5s
pokeapi.httpclient-read-timeout=30s
pokeapi.catalog-fetch-concurrency=20


spring.cache.type=redis
spring.cache.redis.time-to-live=24h
spring.data.redis.host=localhost
spring.data.redis.port=6379

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true
